services:
  3x-ui:
    image: ghcr.io/0x733/3xui-build/debian-xui:latest
    container_name: 3x-ui
    hostname: yourhostname
    volumes:
      - ./db/:/etc/x-ui/
      - ./cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    ports:
      - "9090:9090" 
    restart: unless-stopped