name: Docker Build and Debug Test

on:
  # Haftada bir kez veya bir push olduğunda çalışacak
  schedule:
    - cron: '0 0 * * 1'  # Her Pazartesi 00:00 UTC'de çalışır
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/3x-ui:latest

      - name: Run Docker container for basic debugging
        run: |
          docker run --rm ghcr.io/${{ github.repository }}/3x-ui:latest \
          && echo "Docker container çalıştırıldı!" \
          || echo "Docker container başlatılamadı. Hata ayıklama gerekebilir."

      - name: Check if container starts properly
        run: |
          docker inspect --format='{{.State.Running}}' ghcr.io/${{ github.repository }}/3x-ui:latest \
          && echo "Container is running." \
          || echo "Container is not running."

      - name: List running Docker containers
        run: |
          docker ps