name: Docker Compose Health Check

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-health-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify the installation

      # Step 4: Build and start Docker services
      - name: Start Docker Compose services
        run: docker-compose up -d

      # Step 5: Wait for services to initialize
      - name: Wait for services to be ready
        run: sleep 30  # Adjust sleep time if needed for service startup

      # Step 6: Check health status of Docker services
      - name: Check Docker services health status
        run: |
          services=$(docker-compose ps --services)
          unhealthy=0
          
          for service in $services; do
            health=$(docker inspect --format='{{json .State.Health.Status}}' "$service" 2>/dev/null || echo "null")
            if [ "$health" == "\"unhealthy\"" ]; then
              echo "Service $service is unhealthy!"
              unhealthy=$((unhealthy+1))
            elif [ "$health" == "\"healthy\"" ]; then
              echo "Service $service is healthy."
            else
              echo "Service $service has no healthcheck."
            fi
          done

          if [ "$unhealthy" -gt 0 ]; then
            echo "Some services are unhealthy!"
            exit 1
          else
            echo "All services are healthy."
          fi

      # Step 7: Shutdown Docker Compose services
      - name: Shut down Docker Compose services
        run: docker-compose down