name: Docker and KVM Test

on:
  # Haftada bir kez veya bir push olduğunda çalışacak
  schedule:
    - cron: '0 0 * * 1'  # Her Pazartesi 00:00 UTC'de çalışır
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image with KVM
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/kvm-docker:latest

      - name: Run KVM and Docker inside container
        run: |
          docker run --rm --privileged ghcr.io/${{ github.repository }}/kvm-docker:latest