name: Build and Push Docker Image to GHCR

# Workflow'u tetikleyen eventler
on:
  push:
    branches:
      - main   # Ana branch'e her push'ta çalışır
  workflow_dispatch: # Manuel olarak workflow başlatmak için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repo'yu klonlama
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker'ı kurma
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # GitHub Container Registry (GHCR) için oturum açma
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Docker cache temizliği ve optimizasyon
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Docker imajını build etme
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/debian-xui:latest .

      # Docker imajını GHCR'ye push etme
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/debian-xui:latest